# Name of workflow as seen in Github actions tab
name: github-action-test
# Run workflow manually or on push to master branch
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  # To build the project
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Setup node dependencies
        run: npm install
      - name: Download JSON from Strapi
        run: node download.js
      - name: Extract front end translations
        run: node extract.js
      - name: Encrypt question JSON
        run: node encrypt.js
      - name: Prune question JSON en
        run: cat ./questions-enc-en.json | jq "del(.data[].attributes.createdAt,.data[].attributes.updatedAt,.data[].attributes.enabled,.data[].attributes.quizPack,.data[].attributes.tags,.data[].attributes.locale, .data[].attributes.relatedCountry, .data[].attributes.media.data.attributes.formats, .data[].attributes.answers[].media.data.attributes.formats)" > ./uploads/questions-enc-en.json
